### ISSUE TITLE
Demo Link

### ISSUE THREAD

**Issue by Mosaibah** [mohdShahwan/eat-n-split#1]
Hala Mohammed,
I think u deployed ur app on Github pages, can u please add the deployed link to the Readme file ?

**Comment by mohdShahwan** [comment]
Hello Abdulrahman,

Thank you for bringing up this valuable issue. I wanted to inform you that I have added the demo link to the README file of the app deployed on Github pages. You can now easily access and explore the app using the provided link.

Best regards,
Mohammad
